### ISSUE TITLE
Give feedback or report issues about CMSIS here!

### ISSUE THREAD

**Issue by ReinhardKeil** [ARM-software/CMSIS#1]
This is the place to publish new issues

**Comment by salkinium** [comment]
@ReinhardKeil: Looking around some of you other repositories in ARM-software, I can see that you have accepted contributions before, but those repositories are probably maintained by a different business unit of ARM?

Could you please clarify the following points:
- Does Keil have a process for reviewing and accepting outside contributions? Is this process done via GitHub Pull Requests or do you use an internal system?
- Do you have a Contributor License Agreement (or similar) in place? I suspect this is the main reason why you cannot merge PRs right now.
- Who inside Keil is responsible for community support?

**Comment by ReinhardKeil** [comment]
Hi Salkinium,

you are right, we had legal issues that we have now resolved by using the Apache 2.0 license.
There is also a new GitHub repository for the upcoming CMSIS v5 (https://github.com/ARM-software/CMSIS_5).

We are updating also CMSIS-RTOS to RTX v5 and this will add many features (some from the pull requests will be included but solved slightly different).

**Comment by ReinhardKeil** [comment]
closing as this is misleading now
