### ISSUE TITLE
CMSIS RTOS: thread_id in osMessageCreate?

### ISSUE THREAD

**Issue by senselessDev** [ARM-software/CMSIS#100]
What is the purpose of the `thread_id` parameter in [osMessageCreate](http://www.keil.com/pack/doc/CMSIS/RTX/html/group___c_m_s_i_s___r_t_o_s___message.html#gaf3b9345cf426304d46565152bc26fb78) for?

The documentation is not really telling what it is used for.

**Comment by ilg-ul** [comment]
#61

**Comment by senselessDev** [comment]
Upps, sorry, did not found it.
