### ISSUE TITLE
Comment with Cortex-M4 in core_cm7.h

### ISSUE THREAD

**Issue by mguntli** [ARM-software/CMSIS#108]
Looks like search & replace has missed one entry to be replaced with Cortex-M7:

/* Memory mapping of Cortex-M4 Hardware */
https://github.com/ARM-software/CMSIS/blob/master/CMSIS/Include/core_cm7.h#L1740

**Comment by jkrech** [comment]
Please take a look at the current repository 
https://github.com/ARM-software/CMSIS_5
https://github.com/ARM-software/CMSIS_5/blob/develop/CMSIS/Core/Include/core_cm7.h

**Comment by mguntli** [comment]
Agreed, it's fixed in CMSIS Version 5
