### ISSUE TITLE
Return value of __disable_irq for GCC

### ISSUE THREAD

**Issue by c1728p9** [ARM-software/CMSIS#16]
I noticed that the return type of __disable_irq for gcc is void.  In the armcc version it is a compiler intrinsic which returns the previous state of the global interrupt mask.  I wasn't sure if this was a bug so I opened this issue.

Info on armcc __disable_irq intrinsic:
http://infocenter.arm.com/help/index.jsp?topic=/com.arm.doc.dui0491h/CJAFBCBB.html 

GCC's implementation of __disable_irq:
https://github.com/ARM-software/CMSIS/blob/8c0e1a91341cde86532b05625f2ad584ce856118/CMSIS/Include/cmsis_gcc.h#L69

**Comment by ReinhardKeil** [comment]
The CMSIS specification is clear and does not indicate that we return the current state of the interrupt status.
http://www.keil.com/pack/doc/CMSIS/Core/html/group___core___register__gr.html#gaeb8e5f7564a8ea23678fe3c987b04013

To achieve that functionality we have have used in ARM Compiler Version 4 and 5 and intrinsic function that does a bit more.  However for ARM Compiler 6 we are correcting that to the same functionality of the current GCC implementation (and this will be in-line with the CMSIS specification).
