### ISSUE TITLE
Small typo in mutex page

### ISSUE THREAD

**Issue by ilg-ul** [ARM-software/CMSIS#19]
In the mutex docu [page](http://www.keil.com/pack/doc/CMSIS/RTOS/html/group___c_m_s_i_s___r_t_o_s___mutex_mgmt.html#ga5e1752b73f573ee015dbd9ef1edaba13), the **Status and Error Codes** section reads: 

* _osOK_: the mutex has been **obtain**. <--

**Comment by KeilChris** [comment]
Adding done flag here. Will be available in the CMSIS_5 repo within today.

**Comment by ReinhardKeil** [comment]
closing as there is no further activity

**Comment by ilg-ul** [comment]
what further activity was expected?

the line _'osOK: the mutex has been obtain.'_ should have been replaced by _'osOK: the mutex has been obtained.'_
