### ISSUE TITLE
Add '#define __INLINE         inline' definition for TI compiler in core_cm4.h 

### ISSUE THREAD

**Issue by dd430** [ARM-software/CMSIS#3]
Currently (v4.5.0):
#elif defined ( __TMS470__ )
  #define __ASM            __asm                                      /*!< asm keyword for TI CCS Compiler       */
  #define __STATIC_INLINE  static inline

SHould be changed to:

#elif defined ( __TI_ARM__ )
  #define __ASM            __asm                                      /*!< asm keyword for TI ARM Compiler       */
  #define __INLINE         inline                                     /*!< inline keyword for TI ARM Compiler    */      
  #define __STATIC_INLINE  static inline

**Comment by GuentherMartin** [comment]
Included in CMSIS-Core.

**Comment by ReinhardKeil** [comment]
closing as this is implemented in CMSIS 5 now
