### ISSUE TITLE
CMSIS Documentation: Explain how to create threads with multiple instances

### ISSUE THREAD

**Issue by ilg-ul** [ARM-software/CMSIS#35]
To my surprise, the feature allowing to define multiple instances of a single thread was completely unknown to me, the current documentation for [threads](https://www.keil.com/pack/doc/CMSIS/RTOS/html/group___c_m_s_i_s___r_t_o_s___thread_mgmt.html) does not explain it at all.

Suggested changes:
- document what the `instances` parameter of the `osThreadDef()` macro is, and how multiple instances of a single thread can be created and reused after termination.

**Comment by KeilChris** [comment]
This is already documented here: http://www.keil.com/pack/doc/CMSIS/RTOS/html/group___c_m_s_i_s___r_t_o_s___thread_mgmt.html
The last bullet point item in the description states that "Active threads can be terminated any time using the function osThreadTerminate. Threads can terminate also by just returning from the thread function."

**Comment by ilg-ul** [comment]
done? I updated the suggested changes text, perhaps it was not clear enough.

**Comment by KeilChris** [comment]
Will be available in the CMSIS_5 repo within today.

**Comment by ReinhardKeil** [comment]
Was RTOS1 API and is in the documentation http://www.keil.com/pack/doc/CMSIS/RTOS/html/group__CMSIS__RTOS__ThreadMgmt.html
