### ISSUE TITLE
CMSIS RTOS API: Make the scheme to assign names to objects more consistent 

### ISSUE THREAD

**Issue by ilg-ul** [ARM-software/CMSIS#46]
The macros used to define object names are not consecvent, for example the  thread name is derived from the thread function name, but the timer name should be explicitly defined, different from the timer function.

```
void Thread_1 (void const *arg);                          
osThreadDef (Thread_1, osPriorityNormal, 1, 0); 

void Timer1_Callback  (void const *arg);                  
osTimerDef (Timer1, Timer1_Callback);   

```

In [CMSIS++](http://micro-os-plus.github.io/cmsis-plus/), all objects attributes include the `.name` field, making this mechanism  consistent across all objects.

Suggestion:
- use separate explicit names for all objects.

**Comment by ReinhardKeil** [comment]
CMSIS-RTOS2 has addressed this

**Comment by ReinhardKeil** [comment]
completed
