### ISSUE TITLE
CMSIS RTOS API: Add a mechanism to enumerate all registered threads

### ISSUE THREAD

**Issue by ilg-ul** [ARM-software/CMSIS#51]
For writing monitor commands that list all available threads, it is required to enumerate existing threads.

Suggestion:
- add a standard iterator to allow access to all scheduler registered threads.

**Comment by ReinhardKeil** [comment]
osThreadEnumerate has been added to CMSIS-RTOS2

**Comment by ReinhardKeil** [comment]
completed
