### ISSUE TITLE
CMSIS RTOS API: Add normal (non-recursive) mutex

### ISSUE THREAD

**Issue by ilg-ul** [ARM-software/CMSIS#53]
POSIX defines several mutex types, like normal vs recursive.

In [CMSIS++](http://micro-os-plus.github.io/cmsis-plus/), the attributes used to create mutexes include all  POSIX functionality, included type, robustness, priority ceiling, max count.

Suggestion:
- add an explicit method to create normal and recursive mutexes.

**Comment by ilg-ul** [comment]
for reference, the CMSIS++ page for mutex is:

http://micro-os-plus.github.io/reference/cmsis-plus/classos_1_1rtos_1_1_mutex.html

the attributes used to construct a POSIX compliant mutex are:

http://micro-os-plus.github.io/reference/cmsis-plus/classos_1_1rtos_1_1mutex_1_1_attributes.html

**Comment by ombre5733** [comment]
For reference, [pull-request 15](https://github.com/ARM-software/CMSIS/pull/15) implements such a mutex.

**Comment by ReinhardKeil** [comment]
CMSIS-RTOS2 adds attribute for recursive mutex.

**Comment by ReinhardKeil** [comment]
closing this now as it has been added in CMSIS-RTOS2 already a while back ago
