### ISSUE TITLE
CMSIS RTOS API: Make osSemaphoreWait() return errors, not counts

### ISSUE THREAD

**Issue by ilg-ul** [ARM-software/CMSIS#56]
`osSemaphoreWait()` returns the semaphore count, no errors like all other calls. At least one CMSIS OS port (the ST one) got this wrong, and returned errors.

In [CMSIS++](http://micro-os-plus.github.io/cmsis-plus/), the `wait()`/`try_wait()`/`timed_wait()` all return error codes, and the semaphore count is obtained by the separate `Semaphore::value()` call.

Suggestion
- change osSemaphoreWait() to return status codes
- add a separate function to return the semaphore count

**Comment by ilg-ul** [comment]
for reference, the CMSIS++ documentation for Semaphore is at:

http://micro-os-plus.github.io/reference/cmsis-plus/classos_1_1rtos_1_1_semaphore.html

**Comment by ilg-ul** [comment]
according to Scott Meyers, your design breaks "the principle of least astonishment", you should take advantage of what users already know and maximise the likelihood that they guess correctly.

by making most functions return an error, but osSemaphoreWait() return a count, the chances for users to guess correctly without reading the documentation are close to zero.

**Comment by ReinhardKeil** [comment]
CMSIS-RTOS2 has addressed this

**Comment by ReinhardKeil** [comment]
completed
