### ISSUE TITLE
CMSIS Documentation: Fix misplaced thread id parameter for message queue

### ISSUE THREAD

**Issue by ilg-ul** [ARM-software/CMSIS#59]
In the [Message Queue](http://www.keil.com/pack/doc/CMSIS/RTOS/html/group___c_m_s_i_s___r_t_o_s___message.html) page the explanation note about _thread_ is listed under `osMessageQDef()` instead of `osMessageCreate()` (which generally ignores it, anyway).

**Comment by KeilChris** [comment]
Adding done flag here. Will be available in the CMSIS_5 repo within today.

**Comment by ReinhardKeil** [comment]
Done in CMSIS5 documentation

**Comment by ilg-ul** [comment]
> Done in CMSIS5 documentation

that's good, but even if the RTOSv1 will eventually be deprecated, I think it still should be accurate.
