### ISSUE TITLE
CMSIS RTOS API: Fix non-portable message type in osMessagePut()

### ISSUE THREAD

**Issue by ilg-ul** [ARM-software/CMSIS#60]
The parameter used to pass messages is `uint32_t info` even when a pointer is required.

In particular, for 32-bits cores, this can be fixed with casts, but  for 64-bits platforms this is no longer possible.

As a curious thing, internally RTX uses `void*` as message type, but, for unknown reasons, the CMSIS definition ended up with an integer instead of a pointer.

Suggestion:
- update the queue specs to explicitly store pointers, not integers

**Comment by ReinhardKeil** [comment]
This problem is fixed in CMSIS-RTOS2

**Comment by ReinhardKeil** [comment]
closing as this has been resolved already long time ago - in case that it is not just reopen.
