### ISSUE TITLE
CMSIS RTOS API: Deprecate or remove the unused thread_id parameter in osMessageQCreate()/osMailQCreate() prototypes

### ISSUE THREAD

**Issue by ilg-ul** [ARM-software/CMSIS#61]
The parameter is defined as _Note: The parameter thread registers the receiving thread for a message and is needed for the general osWait function to deliver the message._

However both the RTX and the FreeRTOS implementations ignore this parameter.

**Comment by ilg-ul** [comment]
for reference, the CMSIS++ queue documentation pages is:

http://micro-os-plus.github.io/reference/cmsis-plus/classos_1_1rtos_1_1_message__queue.html

POSIX queues do not require a thread id and I could not find any reasons for passing it when creating new queues.

**Comment by ReinhardKeil** [comment]
closing as RTOS2 has a different implementation
