### ISSUE TITLE
CMSIS RTOS API: Suggestions and comments

### ISSUE THREAD

**Issue by ilg-ul** [ARM-software/CMSIS#64]
During the design and development phases of [CMSIS++](http://micro-os-plus.github.io/cmsis-plus/), I kept a log of issues that I identified and addressed in the CMSIS++ proposal.

Some were difficulties in understanding the CMSIS RTOS API, due to documentation issues, some are functional issues that either do not comply to POSIX or are making using the original API not very convenient, and some are suggestions for missing features.

The POSIX compliance issues are:
- Use POSIX error codes (#65)
- Use explicit separate calls for different waiting functions, like `lock()`, `try_lock()`, `timed_wait()` (#45)
- Add normal (non-recursive) mutex (#53)
- Add a mechanism to wait for a thread to terminate (#50)
- For message queues, make the message size user configurable (#70)
- For message queues, add message priorities (#72)
- Make osSemaphoreWait() return errors, not counts (#56)
- Deprecate or remove the unused thread_id parameter in osMessageQCreate()/osMailQCreate() prototypes (#61)

Some of the functional issues are:
- Avoid the heavy use of macros (to define objects and to refer to them) (#36)
- Do not mandate the use of a dynamic allocator (for stack, queues, etc) (#37)
- Add support for critical regions (interrupts & scheduler) (#38)
- Avoid mixing time durations (in milliseconds) with timer counts in ticks (#39)
- Add a separate RTC system clock (#40)
- Add `os_main()` to make the use of a main thread explicit (#41)
- Add support for a synchronised public memory allocator (#42)
- Avoid returning agregates (like `osEvent`) (#43)
- Extend the range for `osKernelSysTick()` (#44)
- Make the scheme to assign names to objects more consistent (#46)
- Add missing destructor functions to all objects (#47)
- Extend the range of priority levels (#49)
- Add a mechanism to enumerate all registered threads (#51)
- Allow to explicitly define the semaphore max count (#55)
- Add a method to wait for a memory pool block to become available (#57)
- Fix non-portable message type in `osMessagePut()` (#60)
- Fix `osMessagePut()`/`osMailPut()` inconsistent error when called from ISR (#62)
- Mail queues, as separate objects, are redundant (#63)
- Add typedefs for all different types used in prototypes (#66)
- For all objects, add reset functions to return the object to initial status (#67)
- For mutex, add a method to get the owner thread (#68)
- For memory pools, add more accessors to get pool status (#69)
- For message queues, add more accessors to get queue status (#71)

The documentation issues are:
- Explain that thread functions can return (#48)
- Explain the mutex behaviour (recursive vs normal) (#52)
- Clarify the specs for binary vs counting semaphores (#54)
- Fix the data type used in `osMessageQDef()` example (#58)
- Fix misplaced thread id parameter for message queue (#59)

Note: These issues refer to the current public release of CMSIS RTOS API, not to the recently announced CMSIS 5 development version.

For the CMSIS RTOS API v2 proposal, the issues are:
- Move deprecated definitions to a separate file (#75)
- Avoid mandatory dynamic allocation for all objects inadequate due to fragmentation (#76)
- Avoid adding further macros for the attributes (#77)
- When using attributes, avoid unnecessary creation parameters (#78)
- Inconsistent memory allocation for object and object storage (#79)
- Fix inconsistent type naming convention (#80)
- `osEventFlagsWait()`/`osThreadFlagsWait()` return type inconsistent with other blocking calls (#81)

**Comment by ReinhardKeil** [comment]
this was a very good summary, but I'm closing it now as most of the stuff has been addressed
