### ISSUE TITLE
CMSIS RTOS API: For mutex, add a method to get the owner thread

### ISSUE THREAD

**Issue by ilg-ul** [ARM-software/CMSIS#68]
In [CMSIS++](http://micro-os-plus.github.io/cmsis-plus/), if a mutex is locked, it is possible to know which thread locked the mutex.

Suggestion:
- add an `owner()` function to return a pointer to the thread that owns the mutex

**Comment by ReinhardKeil** [comment]
osMutexGetOwner has been added to CMSIS-RTOS2

**Comment by ReinhardKeil** [comment]
completed
