### ISSUE TITLE
CMSIS RTOS API: For memory pools, add more accessors to get pool status

### ISSUE THREAD

**Issue by ilg-ul** [ARM-software/CMSIS#69]
In CMSIS RTOS API, once created, a memory pool has no functions to tell if the pool is empty or full, to get the block size, the pool capacity, and so on.

In [CMSIS++](http://micro-os-plus.github.io/cmsis-plus/) all memory pool characteristics are available via accessor functions.

```
std::size_t
capacity (void) const;

std::size_t
count (void) const;

std::size_t
block_size (void) const;

bool
empty (void) const;

bool
full (void) const;
```

Suggestion:
- add accessor functions for memory pool status

**Comment by ReinhardKeil** [comment]
CMSIS-RTOS2 adds the requested features
http://arm-software.github.io/CMSIS_5/RTOS2/html/group__CMSIS__RTOS__PoolMgmt.html

**Comment by ReinhardKeil** [comment]
closing as there is no further activity
