### ISSUE TITLE
core_cm7.h - SCB_EnableDCache()  not working with IAR / GCC

### ISSUE THREAD

**Issue by ben0809ST** [ARM-software/CMSIS#7]
Hi,

in all functions dealing with cache, there are defines for only __CC_ARM :

#if defined ( __CC_ARM )
          __schedule_barrier();
 #endif

should be updated to add others compilers IAR/GCC or to implement something  more generic similar to 
       
       #if defined ( __CC_ARM )
          __schedule_barrier();
        #else
          __DSB();
        #endif
or replacing __schedule_barrier();  by __DSB();

Thank you for a feedback.

**Comment by ReinhardKeil** [comment]
The __schedule_barrier is a work-around for a potential compiler issue.  It is not required in other compilers.
