### ISSUE TITLE
CMSIS RTOS API v2: Move deprecated definitions to a separate file

### ISSUE THREAD

**Issue by ilg-ul** [ARM-software/CMSIS#75]
Browsing through the proposal for the new `cmsis_os.h`, I noticed that perhaps more than half of it is now deprecated and requires the presence of the `osCMSIS_API_V1` macro.

Advanced editors like Eclipse can show the unused lines as grey, but it is still difficult to read such a file.

Suggestion:

* move all deprecated definitions to a separate file, and explicitly mark them as 'Not recommended for new designs'

**Comment by ReinhardKeil** [comment]
Cosmetic
