### ISSUE TITLE
CMSIS RTOS API v2: Avoid mandatory dynamic allocation for all objects inadequate due to fragmentation

### ISSUE THREAD

**Issue by ilg-ul** [ARM-software/CMSIS#76]
The first major change I noticed in RTOS API v2 reads:

```
OS object's resources dynamically allocated rather than statically:
- added: osXxxxNew functions which replace osXxxxCreate
- removed: osXxxxCreate functions, osXxxxDef_t structures
```

Implementing this requires either a set of statically configured pools for each object type (separate pools for threads, mutexes, semaphores, pools, queues, mailboxes, flags, etc), which is highly discouraged, or the use of a true dynamic allocator, which is inacceptable for many applications due to fragmentation.

[CMSIS++](http://micro-os-plus.github.io/cmsis-plus/) gives the user full control of the location where the objects are allocated, similar to C++, in other words objects can be statically allocated in the BSS, on the thread stack or on the heap (with a dynamic allocator like malloc()).

Suggestion:

* add a first parameter to the object creation function, with a pointer to a structure where the object will be emplaced; if this pointer is null, the object will be allocated dynamically using an implementation specific allocator.

**Comment by ReinhardKeil** [comment]
Wait for documentation here.
