### ISSUE TITLE
CMSIS RTOS API v2: Avoid adding further macros for the attributes

### ISSUE THREAD

**Issue by ilg-ul** [ARM-software/CMSIS#77]
I noticed that, probably inspired by CMSIS++, you added attributes to control the creation of new objects. This is actually the POSIX approach, and I think it is ok.

However you also added lots of macros to initialise these attributes, and this is not really POSIX, and not really a good idea.

The major POSIX argument for using attributes, is that they can be easily extended in future versions, without breaking compatibility with existing versions.

For this to work, POSIX has functions that initialise the attributes to convenient defaults, then each attribute is set/get, in a single line, with a specialised setter/getter. In POSIX, adding a new parameter requires only adding a new setter/getter, which does not break compatibility.

In CMSIS RTOS API v2 you use macros with lots of arguments, which may be compact, but if in a future version you'll need to add a new argument, you'll have to either extend the macro, or set the attribute manually in the structure, which is inconsistent.

In [CMSIS++](http://micro-os-plus.github.io/cmsis-plus/) all attribute objects are initialised with a similar looking constructor, with a single argument (the object name). All other attributes are consistently set by directly manipulating the structure members.

For example, in the compatibility wrapper, the implementation of `osThreadCreate()` includes:

```
  thread::Attributes attr
    { thread_def->name };
  attr.th_priority = thread_def->tpriority;
  attr.th_stack_size_bytes = thread_def->stacksize;
  ...
  new (th) Thread (attr, (thread::func_t) thread_def->pthread, args);
```

Suggestion:

* use a consistent, similar loooking, method to initialise all objects with default values and explictly set structure members for each attribute.

**Comment by ReinhardKeil** [comment]
Understood, give us time to finish it!
