### ISSUE TITLE
ARM_MATH_CM0_FAMILY and SIMD in DSP_Lib

### ISSUE THREAD

**Issue by sw** [ARM-software/CMSIS#91]
Many DSP functions have SIMD optimizations, for example `arm_cfft_q15`. The optimized versions are selected by the absence of the `ARM_MATH_CM0_FAMILY` macro.

The macro `ARM_MATH_CM0_FAMILY` is defined in arm_math.h for Cortex-M0 processors.

But Cortex-M3 processors do not have the SIMD instructions. This leads to quite inefficient code on Cortex-M3 processors, because the SIMD instructions such as `__SHADD16` are emulated by the functions defined in arm_math.h

The lines
`#ifndef ARM_MATH_CM0_FAMILY`
should be changed to
`#if !defined (ARM_MATH_CM3) && !defined (ARM_MATH_CM0_FAMILY)`

I suspect this affects all modules there the existence of ARM_MATH_CM0_FAMILY is checked.

**Comment by sw** [comment]
Also seems to affect the CMSIS_5 repository

**Comment by GuentherMartin** [comment]
Selection is now done via macro ARM_MATH_DSP.
ARM_MATH_DSP specifies if DSP instructions should be used.
Please see https://github.com/ARM-software/CMSIS_5/commit/ec3081af4b42309566f1180dcb3f9db8508c7aa4.

**Comment by ReinhardKeil** [comment]
released as part of CMSIS 5.0.1
