### ISSUE TITLE
No const definitions for real input FFT instances

### ISSUE THREAD

**Issue by apullin** [ARM-software/CMSIS#92]
There are no structure instances for the RFFT functions following the style of the CFFT structures. The downside to this is that if you are looping over several lengths, the compiler cannot select only the necessary twiddle factor tables. This can overrun flash for small devices quickly. Maybe in the case that an author is careful about declaring const values and the right optimizations are on.

I added definitions for the RFFT instances following the same pattern as the provided ones, and I am pretty sure that these are all defined in the same way that the init function would configure them at runtime:
https://github.com/apullin/CMSIS/tree/real_fft_const

The documentation in the "Real FFT" section on how to set these up is quite terse. For most end-user applications, input data is likely going to be all real-valued, so providing these instances should be useful.

Let me know if I should issue a pull request.

**Comment by GuentherMartin** [comment]
Struct instances added to arm_const_structs.c.
Please see https://github.com/ARM-software/CMSIS_5/commit/ec3081af4b42309566f1180dcb3f9db8508c7aa4.

**Comment by apullin** [comment]
Aw, I wanted to get a commit pulled into DSP-Lib, that would have been pro-status! Oh well.

**Comment by ReinhardKeil** [comment]
released as part of CMSIS 5.0.1

**Comment by apullin** [comment]
There does not appear to be declarations in arm_const_structs.h for the defined constant structures?
