### ISSUE TITLE
GCC Debug issue in ARM Keil

### ISSUE THREAD

**Issue by peyman477** [ARM-software/CMSIS#93]
Hello, I've written and compiled a simple C program to be simulated on ARM CM7 microprocessor within ARM Keil IDE (CMSIS Core 4.3 & GNU Tools ARM Embedded 4.9 2015.q2). The program compiles without any warnings or errors. Yet, when debugging through the ARM Keil the program gets stuck at system_ARMCM7.c file at the line

SystemCoreClock = SYSTEM_CLOCK;

Checking the "Performance analyzer" component of the Keil I can see the program is stuck at the _exit function/module of the system_ARMCM7.c file.

Unfortunately I can't figure out what is causing the issue. Would anybody please come up with some suggestions? (This happens with various ARM devices e.g. CM4, CM7)

Sincerely,

Peyman

**Comment by ReinhardKeil** [comment]
Sorry, but this is not a support forum for the Keil tools.  Please contact the standard support channels.
See www.keil.com/support.
